In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("../data/earthquake.csv")

In [13]:
fit_df = df.sample(frac=0.39, axis=0, random_state=10)

In [14]:
fit_df

,time,place,status,tsunami,significance,data_type,magnitudo,state,longitude,latitude,depth,date
2893144,1579656298779,"40 km W of Adak, Alaska",reviewed,0,22,earthquake,1.20,Alaska,-177.225100,51.868500,5.900,2020-01-22 01:24:58.779000+00:00
503337,869913415360,"12 km SSW of Mammoth Lakes, California",reviewed,0,36,earthquake,1.54,California,-119.005833,37.541333,2.840,1997-07-26 10:36:55.360000+00:00
433472,832733978940,"3 km E of Rezzo, Italy",reviewed,0,112,earthquake,2.70,Italy,7.910000,44.019000,5.000,1996-05-22 02:59:38.940000+00:00
1932628,1345326379302,"2 km S of Sun Valley, Nevada",reviewed,0,10,earthquake,0.80,Nevada,-119.779400,39.577000,9.000,2012-08-18 21:46:19.302000+00:00
1690290,1274832747915,"12 km NE of Healy, Alaska",reviewed,0,62,explosion,2.00,Alaska,-148.779600,63.933600,0.000,2010-05-26 00:12:27.915000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2097486,1390717720500,"3 km W of Cobb, California",automatic,0,1,earthquake,0.29,California,-122.764664,38.820667,1.809,2014-01-26 06:28:40.500000+00:00
1609243,1246340240015,"55 km E of Pedro Bay, Alaska",reviewed,0,50,earthquake,1.80,Alaska,-153.122600,59.766200,105.700,2009-06-30 05:37:20.015000+00:00
563199,892194848880,"58 km S of Cordova, Alaska",reviewed,0,44,earthquake,1.70,Alaska,-145.707000,60.018200,-3.000,1998-04-10 07:54:08.880000+00:00
1299201,1153880261680,"7 km W of Cobb, California",reviewed,0,15,earthquake,0.99,California,-122.806667,38.830500,0.882,2006-07-26 02:17:41.680000+00:00
1967053,1355048020720,"224 km ESE of ?funato, Japan",reviewed,0,326,earthquake,4.60,Japan,143.937000,38.050000,21.500,2012-12-09 10:13:40.720000+00:00

In [15]:
fit_df.to_csv("../data/earthquake_dataset.csv")

In [16]:
fit_df.index

Index([2893144,  503337,  433472, 1932628, 1690290, 3020503,  635283, 1777965,
       1895803, 2792440,
       ...
        986282, 1386322, 2390166, 2733022,  472363, 2097486, 1609243,  563199,
       1299201, 1967053],
      dtype='int64', length=1343843)

In [17]:
real_time_data = df.drop(fit_df.index, axis=0)

In [18]:
real_time_data.to_csv("../data/real_time_data.csv")

In [19]:
real_time_data

,time,place,status,tsunami,significance,data_type,magnitudo,state,longitude,latitude,depth,date
2,631154083450,"7 km W of Cobb, California",reviewed,0,19,earthquake,1.11,California,-122.806167,38.821000,3.220,1990-01-01 00:34:43.450000+00:00
4,631155824490,"16km N of Fillmore, CA",reviewed,0,134,earthquake,2.95,California,-118.934000,34.546000,16.122,1990-01-01 01:03:44.490000+00:00
7,631156431950,"12 km E of Mammoth Lakes, California",reviewed,0,11,earthquake,0.83,California,-118.834167,37.661500,0.556,1990-01-01 01:13:51.950000+00:00
8,631156614070,"11 km E of Mammoth Lakes, California",reviewed,0,39,earthquake,1.59,California,-118.840167,37.662333,-0.234,1990-01-01 01:16:54.070000+00:00
9,631156620210,"1 km W of Wilkeson, Washington",reviewed,0,74,earthquake,2.20,Washington,-122.071167,47.102500,8.382,1990-01-01 01:17:00.210000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
3445741,1690625310020,"4 km SW of Redlands, CA",automatic,0,16,earthquake,1.01,California,-117.215500,34.030167,14.450,2023-07-29 10:08:30.020000+00:00
3445742,1690625393345,Southern Alaska,automatic,0,22,earthquake,1.20,Southern Alaska,-152.159400,60.104900,53.900,2023-07-29 10:09:53.345000+00:00
3445743,1690626164400,"16 km ESE of Julian, CA",automatic,0,11,earthquake,0.85,California,-116.432833,33.035833,7.370,2023-07-29 10:22:44.400000+00:00
3445748,1690627215940,"12 km W of Alberto Oviedo Mota, B.C., MX",automatic,0,90,earthquake,2.42,B.C.,-115.296833,32.233167,1.770,2023-07-29 10:40:15.940000+00:00
3445750,1690628937884,"35 km W of Karluk, Alaska",automatic,0,12,earthquake,0.90,Alaska,-155.051000,57.564800,250.000,2023-07-29 11:08:57.884000+00:00

In [20]:
len(real_time_data) / 2

1050954.0

In [21]:
real_time_data = pd.read_csv("../data/real_time_data.csv", index_col=0)

:

In [ ]:
real_time_data

,time,place,status,tsunami,significance,data_type,magnitudo,state,longitude,latitude,depth,date
2,631154083450,"7 km W of Cobb, California",reviewed,0,19,earthquake,1.11,California,-122.806167,38.821000,3.220,1990-01-01 00:34:43.450000+00:00
4,631155824490,"16km N of Fillmore, CA",reviewed,0,134,earthquake,2.95,California,-118.934000,34.546000,16.122,1990-01-01 01:03:44.490000+00:00
7,631156431950,"12 km E of Mammoth Lakes, California",reviewed,0,11,earthquake,0.83,California,-118.834167,37.661500,0.556,1990-01-01 01:13:51.950000+00:00
8,631156614070,"11 km E of Mammoth Lakes, California",reviewed,0,39,earthquake,1.59,California,-118.840167,37.662333,-0.234,1990-01-01 01:16:54.070000+00:00
9,631156620210,"1 km W of Wilkeson, Washington",reviewed,0,74,earthquake,2.20,Washington,-122.071167,47.102500,8.382,1990-01-01 01:17:00.210000+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
3445741,1690625310020,"4 km SW of Redlands, CA",automatic,0,16,earthquake,1.01,California,-117.215500,34.030167,14.450,2023-07-29 10:08:30.020000+00:00
3445742,1690625393345,Southern Alaska,automatic,0,22,earthquake,1.20,Southern Alaska,-152.159400,60.104900,53.900,2023-07-29 10:09:53.345000+00:00
3445743,1690626164400,"16 km ESE of Julian, CA",automatic,0,11,earthquake,0.85,California,-116.432833,33.035833,7.370,2023-07-29 10:22:44.400000+00:00
3445748,1690627215940,"12 km W of Alberto Oviedo Mota, B.C., MX",automatic,0,90,earthquake,2.42,B.C.,-115.296833,32.233167,1.770,2023-07-29 10:40:15.940000+00:00
3445750,1690628937884,"35 km W of Karluk, Alaska",automatic,0,12,earthquake,0.90,Alaska,-155.051000,57.564800,250.000,2023-07-29 11:08:57.884000+00:00

In [ ]:
ent = next(real_time_data.iterrows())

In [ ]:
ent[1]

time                                631154083450
place                 7 km W of Cobb, California
status                                  reviewed
tsunami                                        0
significance                                  19
data_type                             earthquake
magnitudo                                   1.11
state                                 California
longitude                            -122.806167
latitude                                  38.821
depth                                       3.22
date            1990-01-01 00:34:43.450000+00:00
Name: 2, dtype: object